### ISSUE TITLE
In Python module, detrend_opt='off' throws error

### ISSUE THREAD

**Issue by subhacom** [preraulab/multitaper_toolbox#2]
The Python module for multitaper spectral estimation has a bug: `detrend_opt='off'` results in:

```
ValueError: 'off' is not a valid argument for detrend_opt. The choices are: 'constant', 'linear', or 'off'.
```

The buggy section of the code is in `process_input` function:

```
 if detrend_opt != 'linear':
        if detrend_opt in ['const', 'constant']:
            detrend_opt = 'constant'
        elif detrend_opt in ['none', 'false']:
            detrend_opt = 'off'
        else:
            raise ValueError("'" + str(detrend_opt) + "' is not a valid argument for detrend_opt. The choices " +
                             "are: 'constant', 'linear', or 'off'.")
```
This converts 'none' or 'false' to detrend_opt='off', but fails when detrend_opt='off' is passed.

**Comment by thpossidente** [comment]
Thank you very much for bringing this bug to our attention. I have added 'off' to the elif statement in line 260 and the bug is fixed.
