### ISSUE TITLE
Deprecation Warning for ragged array in Python version

### ISSUE THREAD

**Issue by thpossidente** [preraulab/multitaper_toolbox#3]
Warning produced when running python multitaper on 15s snippet of merging example data and with random data

Warning text:

python3.10/site-packages/numpy/lib/arraysetops.py:272: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  ar = np.asanyarray(ar)

**Comment by mh105** [comment]
This is a known deprecation issue of `numpy`. I believe it was triggers when you called `np.where()`. Should be harmless and is automatically suppressed after the first run.
